# Generated by Django 2.2 on 2021-09-22 23:36

from django.db import migrations, models
import irisApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('irisApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_files', to='irisApp.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', upload_to=irisApp.models.pp_path),
        ),
    ]
