# Generated by Django 2.2 on 2021-09-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irisApp', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
