# Generated by Django 2.2 on 2021-09-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irisApp', '0002_auto_20210922_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
