# Generated by Django 2.2 on 2021-09-22 01:55

from django.db import migrations, models
import irisApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('irisApp', '0010_auto_20210921_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
