# Generated by Django 2.2 on 2021-09-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irisApp', '0012_auto_20210922_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
